---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/minikube version
      register: minikube_test_output
    - name: minikube version
      debug:
        msg: '{{ minikube_test_output.stdout }}'
