---
- name: Testing andrewrothstein.minikube
  hosts: all
  vars:
    minikube_install_drivers:
      - kvm2
      - hyperkit
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'minikube version'
      ansible.builtin.command: /usr/local/bin/minikube version
      changed_when: false
      register: minikube_test_output
    - name: Output from 'minikube version'
      ansible.builtin.debug:
        msg: '{{ minikube_test_output.stdout }}'
