---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: downloading {{ minikube_url }}
  become: true
  become_user: root
  get_url:
    url: '{{ minikube_url }}'
    dest: '{{ minikube_install_target }}'
    checksum: '{{ minikube_checksum }}'
    mode: 0755

- name: linking {{ minikube_install_link }} to {{ minikube_install_target }}
  become: true
  become_user: root
  file:
    src: '{{ minikube_install_target }}'
    dest: '{{ minikube_install_link }}'
    state: link

- name: installing drivers...
  with_items: '{{ minikube_install_drivers | default([]) }}'
  include_tasks: '{{ item }}.yml'
