---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.kubectl
  ansible.builtin.include_role:
    name: andrewrothstein.kubectl
- name: Downloading {{ minikube_url }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ minikube_url }}'
    dest: '{{ minikube_install_target }}'
    checksum: '{{ minikube_checksum }}'
    mode: '755'

- name: Linking {{ minikube_install_link }} to {{ minikube_install_target }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ minikube_install_target }}'
    dest: '{{ minikube_install_link }}'
    state: link

- name: Installing drivers...
  loop_control:
    loop_var: driver
  loop: '{{ minikube_install_drivers | default([]) }}'
  ansible.builtin.include_tasks: '{{ driver }}.yml'
